#!/bin/bash

sa818 --port /dev/ttyAMA0 volume --level 1
sa818 --port /dev/ttyAMA0 radio --frequency 439.100 --squelch 8
# --ctcss 94.8,94.8
#https://www.iaru-r1.org/wp-content/uploads/2021/03/UHF-Bandplan.pdf
sa818 --port /dev/ttyAMA0 filters --emphasis no --highpass no --lowpass no
