#!/bin/bash

run() {
  exec=$1
  printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

OLDFREQ=$(grep freq /usr/sbin/hotspot | awk '{ print $6}')
OLDCALL=$(cat /etc/svxlink/svxlink.conf | grep CALL | head -n 1 | tr "=" "\n" | tail -n 1)
if [[ "${OLDCALL}" == *"--"* ]]; then
  OLDCALL="ON0RFG"
fi
OLDSVXREFL=$(cat /etc/svxlink/svxlink.conf | grep HOSTS | head -n 1 | tr "=" "\n" | tail -n 1)
if [[ "${OLDSVXREFL}" == *"--"* ]]; then
  OLDSVXREFL="hostname"
fi
OLDSVXCALL=$(cat /etc/svxlink/svxlink.conf | grep CALLSIGN | tr "=" "\n" | grep \" | tr -cd '[:alnum:]._-')
if [[ "${OLDSVXCALL}" == *"--"* ]]; then
  OLDSVXCALL="ON0RFG"
fi
OLDSVXPWD=$(cat /etc/svxlink/svxlink.conf | grep AUTH_KEY | head -n 1 | tr "=" "\n" | tail -n 1 | tr -cd '[:alnum:]._-')
if [[ "${OLDSVXPWD}" == *"--"* ]]; then
  OLDSVXPWD="secret"
fi

gum style --border normal --margin "1" --padding "1 2" --border-foreground "#04B575" "$(gum style --foreground 3 'RF.')Guru $(gum style --foreground 3 '-') Hotspot Config"

gum style --foreground "#04B575" "Callsign:"
CALL=$(gum input --placeholder "${OLDCALL}")
if [[ "${CALL}" == "" ]]; then
  CALL=${OLDCALL}
fi
gum style --foreground 212 "${CALL}"

gum style --foreground "#04B575" "SVXLink Reflector <IP> or <FQDN>:"
REFLECTOR=$(gum input --placeholder "${OLDSVXREFL}")
if [[ "${REFLECTOR}" == "" ]]; then
  REFLECTOR=${OLDSVXREFL}
fi
gum style --foreground 212 "${REFLECTOR}"

gum style --foreground "#04B575" "SVXLINK Reflector Callsign:"
SVXCALL=$(gum input --placeholder "${OLDSVXCALL}")
if [[ "${SVXCALL}" == "" ]]; then
  SVXCALL=${OLDSVXCALL}
fi
gum style --foreground 212 "${SVXCALL}"

gum style --foreground "#04B575" "SVXLink Reflector password:"
SVXPWD=$(gum input --placeholder "${OLDSVXPWD}")
if [[ "${SVXPWD}" == "" ]]; then
  SVXPWD=${OLDSVXPWD}
fi
gum style --foreground 212 "${SVXPWD}"

gum style --foreground "#04B575" "Band:"
BAND=$(gum choose "70cm" "2m")
gum style --foreground 212 "${BAND}"

gum style --foreground "#04B575" "Frequency:"
if [ "${BAND}" = "70cm" ]; then
  if (( $(echo "${OLDFREQ} > 400" |bc -l) )); then
    FREQ=$(gum input --value "${OLDFREQ}")
  else
    FREQ=$(gum input --value "439.100")
  fi
fi

if [ "${BAND}" = "2m" ]; then
  if (( $(echo "${OLDFREQ} < 400" |bc -l) )); then
    FREQ=$(gum input --value "${OLDFREQ}")
  else
    FREQ=$(gum input --value "145.250")
  fi
fi

gum style --foreground 212 "${FREQ}"

gum style --foreground "#04B575" "Enter CTCSS tone:"
TONE=$(gum input --value "131.8")
gum style --foreground 212 "${TONE}"

gum confirm "Commit changes?"

RESULT=$?
if [ $RESULT -eq 0 ]; then
  say "Downloading latest config template"
  run "wget -O /tmp/svxlink.conf https://raw.githubusercontent.com/Guru-RF/SVXSpot/master/svxlink.conf > /dev/null 2>&1"
  run "wget -O /tmp/ModuleEchoLink.conf https://raw.githubusercontent.com/Guru-RF/SVXSpot/master/ModuleEchoLink.conf > /dev/null 2>&1"
  say "Applying configuration"
  cp /tmp/svxlink.conf /etc/svxlink/svxlink.conf
  cp /tmp/svxlink.conf /etc/svxlink/ModuleEchoLink.conf
  cp /tmp/svxlink.conf /etc/svxlink/svxlink.d/ModuleEchoLink.conf
	perl -i -pe "s/--HOST--/${REFLECTOR}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--CALL--/${CALL}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--SVXCALL--/${SVxCALL}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--PWD--/${PWD}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--ELCALL--/${ELCALL}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--ELPWD--/${ELPWD}/g" /etc/svxlink/svxlink.conf
  ModuleEchoLink.conf
	rm /usr/sbin/hotspot
  echo "sa818 --port /dev/ttyAMA0 volume --level 1" > /usr/sbin/hotspot
  echo "sa818 --port /dev/ttyAMA0 radio --frequency ${FREQ} --ctcss ${TONE} --squelch 8" >> /usr/sbin/hotspot
  echo "sa818 --port /dev/ttyAMA0 filters --emphasis yes --highpass no --lowpass no" >> /usr/sbin/hotspot
	chmod +x /usr/sbin/hotspot
  /usr/sbin/hotspot
	systemctl restart svxlink
else
gum style --foreground "#04B575" "Abort!"
fi

say "Send CTCSS ${TONE} to ${FREQ} with D1# to activate the parrot (to test audio levels)"
say "Send CTCSS ${TONE} to ${FREQ} with D2# to activate EchoLink test room (to test audio levels)"
say "Send CTCSS ${TONE} to ${FREQ} with D3# to activate EchoLink repeater ON0WV"
say "Send CTCSS ${TONE} to ${FREQ} once activat the repeater talkgrou TG8, next PTT you are life on the repeater talkgroup"
say "You here a small two tone when we are back in listening mode on TG0, when there is traffic on TG8 it will be automaticaly activated !"
