#!/bin/bash

sa818 --port /dev/ttyAMA0 volume --level 1
sa818 --port /dev/ttyAMA0 radio --frequency 145.250 --squelch 8
# --ctcss 94.8,94.8
# https://www.iaru-r1.org/wp-content/uploads/2020/12/VHF-Bandplan.pdf
# Use for internal CTCSS encoding of the RF Module
#sa818 --port /dev/ttyAMA0 filters --emphasis no --highpass no --lowpass no
# deemphasis and ctcss decoding in svxlink
sa818 --port /dev/ttyAMA0 filters --emphasis yes --highpass yes --lowpass yes

