#!/bin/bash

TERM=xterm-256color

run() {
  exec=$1
  printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

OLDCPVOL=$(grep volume /usr/sbin/hotspot | awk '{ print $6}'| tail -n 1)
OLDRFVOL=$(grep Capture /usr/sbin/hotspot_volume | awk '{ print $4}'| tail -n 1 | sed 's/%$//')
OLDAFVOL=$(grep Headphone /usr/sbin/hotspot_volume | awk '{ print $4}'| tail -n 1 | sed 's/%$//')
OLDFREQ=$(grep freq /usr/sbin/hotspot | awk '{ print $6}')
OLDTONE=$(grep ctcss /usr/sbin/hotspot | awk '{ print $8}' | tr "," "\n" | tail -n 1)
OLDCALL=$(cat /etc/svxlink/svxlink.conf | grep CALL | head -n 1 | tr "=" "\n" | tail -n 1)
OLDTG=$(cat /etc/svxlink/svxlink.conf | grep DEFAULT_TG | head -n 1 | tr "=" "\n" | tail -n 1)
OLDTGS=$(cat /etc/svxlink/svxlink.conf | grep MONITOR_TGS | head -n 1 | tr "=" "\n" | tail -n 1)
OLDLOCATION=$(grep -i location /etc/svxlink/node_info.json  | awk '{ print $2}' | tr "," "\n" | tr -cd '[:alnum:]._-')
OLDLAT=$(grep -i lat /etc/svxlink/node_info.json  | awk '{ print $2}' | tr "," "\n" | tr -cd '[:alnum:]._-')
OLDLON=$(grep -i lon /etc/svxlink/node_info.json  | awk '{ print $2}' | tr "," "\n" | tr -cd '[:alnum:]._-')
OLDLOC=$(grep -i loc /etc/svxlink/node_info.json  | awk '{ print $2}' | tr "," "\n" | tail -n 1 |  tr -cd '[:alnum:]._-')
QSYTIMEOUT=$(cat /etc/svxlink/svxlink.conf | grep QSY_PENDING_TIMEOUT | head -n 1 | tr "=" "\n" | tail -n 1)
if [[ "${OLDTG}" == *"--"* ]]; then
  OLDTG=8
fi
if [[ "${OLDTGS}" == *"--"* ]]; then
  OLDTGS=8
fi
if [[ "${OLDLAT}" == *"--"* ]]; then
  OLDLAT="50.4707972"
fi
if [[ "${OLDLON}" == *"--"* ]]; then
  OLDLON="3.8624516"
fi
if [[ "${OLDLOC}" == *"--"* ]]; then
  OLDLOC="JO10VK"
fi
if [[ "${OLDCALL}" == *"--"* ]]; then
  OLDCALL="ON0RFG"
fi
OLDSVXREFL=$(cat /etc/svxlink/svxlink.conf | grep HOSTS | head -n 1 | tr "=" "\n" | tail -n 1)
if [[ "${OLDSVXREFL}" == *"--"* ]]; then
  OLDSVXREFL="hostname"
fi
if [[ "${OLDSVXREFL}" == "34.77.14.144" ]]; then
  OLDSVXREFL="hotspots.rf.guru"
fi
OLDSVXCALL=$(cat /etc/svxlink/svxlink.conf | grep CALLSIGN | tr "=" "\n" | grep \" | tr -cd '[:alnum:]._-')
if [[ "${OLDSVXCALL}" == *"--"* ]]; then
  OLDSVXCALL="ON0RFG"
fi
OLDSVXPWD=$(cat /etc/svxlink/svxlink.conf | grep AUTH_KEY | head -n 1 | tr "=" "\n" | tail -n 1 | tr -cd '[:alnum:]._-')
if [[ "${OLDSVXPWD}" == *"--"* ]]; then
  OLDSVXPWD="secret"
fi

gum style --border normal --margin "1" --padding "1 2" --border-foreground "#04B575" "$(gum style --foreground 3 'RF.')Guru $(gum style --foreground 3 '-') Hotspot Config"

gum style --foreground "#04B575" "Callsign:"
CALL=$(gum input --value "${OLDCALL}")
if [[ "${CALL}" == "" ]]; then
  CALL=${OLDCALL}
fi
gum style --foreground 212 "${CALL}"

gum style --foreground "#04B575" "SVXLink Reflector <IP> or <FQDN>:"
REFLECTOR=$(gum input --value "${OLDSVXREFL}")
if [[ "${REFLECTOR}" == "" ]]; then
  REFLECTOR=${OLDSVXREFL}
fi
if [[ "${REFLECTOR}" == "34.77.14.144" ]]; then
  REFLECTOR="hotspots.rf.guru"
fi
gum style --foreground 212 "${REFLECTOR}"

gum style --foreground "#04B575" "SVXLINK Reflector User Callsign:"
SVXCALL=$(gum input --value "${OLDSVXCALL}")
if [[ "${SVXCALL}" == "" ]]; then
  SVXCALL=${OLDSVXCALL}
fi
gum style --foreground 212 "${SVXCALL}"

gum style --foreground "#04B575" "SVXLink Reflector password:"
SVXPWD=$(gum input --value "${OLDSVXPWD}")
if [[ "${SVXPWD}" == "" ]]; then
  SVXPWD=${OLDSVXPWD}
fi
gum style --foreground 212 "${SVXPWD}"

gum style --foreground "#04B575" "Band:"
BAND=$(gum choose "70cm" "2m")
gum style --foreground 212 "${BAND}"


gum style --foreground "#04B575" "Frequency:"
if [ "${BAND}" = "70cm" ]; then
  if [[ "${OLDFREQ}" == "" ]]; then
    OLDFREQ="439.100"
  fi
  if (( $(echo "${OLDFREQ} > 400" |bc -l) )); then
    FREQ=$(gum input --value "${OLDFREQ}")
  else
    FREQ=$(gum input --value "439.100")
  fi
fi

if [ "${BAND}" = "2m" ]; then
  if [[ "${OLDFREQ}" == "" ]]; then
    OLDFREQ="145.250"
  fi
  if (( $(echo "${OLDFREQ} < 400" |bc -l) )); then
    FREQ=$(gum input --value "${OLDFREQ}")
  else
    FREQ=$(gum input --value "145.250")
  fi
fi

gum style --foreground 212 "${FREQ}"

gum style --foreground "#04B575" "Enter CTCSS tone:"
if [[ "${OLDTONE}" == "" ]]; then
  OLDTONE="88.5"
fi
TONE=$(gum input --value "${OLDTONE}")
gum style --foreground 212 "${TONE}"

gum style --foreground "#04B575" "CTCSS on tx:"
CTCSSTX=$(gum choose "Yes" "No")
gum style --foreground 212 "${CTCSSTX}"

gum style --foreground "#04B575" "Enter Location:"
if [[ "${OLDLOCATION}" == "" ]]; then
  OLDLOCATION="Saint Ghislain"
fi
LOCATION=$(gum input --value "${OLDLOCATION}")
gum style --foreground 212 "${LOCATION}"

gum style --foreground "#04B575" "Enter Latitude:"
if [[ "${OLDLAT}" == "" ]]; then
  OLDLAT="50.4707972"
fi
LAT=$(gum input --value "${OLDLAT}")
gum style --foreground 212 "${LAT}"

gum style --foreground "#04B575" "Enter Longitude:"
if [[ "${OLDLON}" == "" ]]; then
  OLDLON="3.8624516"
fi
LON=$(gum input --value "${OLDLON}")
gum style --foreground 212 "${LON}"

gum style --foreground "#04B575" "Enter Gridsquare:"
if [[ "${OLDLOC}" == "" ]]; then
  OLDLOC="JO10VK"
fi
LOC=$(gum input --value "${OLDLOC}")
gum style --foreground 212 "${LOC}"

gum style --foreground "#04B575" "Hide Location info ?:"
HIDDEN=$(gum choose "False" "True")
gum style --foreground 212 "${HIDDEN}"

gum style --foreground "#04B575" "Enter default talk group:"
if [[ "${OLDTG}" == "" ]]; then
  OLDTG=8
fi
TG=$(gum input --value "${OLDTG}")
gum style --foreground 212 "${TG}"

gum style --foreground "#04B575" "Enter talk groups to monitor:"
if [[ "${OLDTGS}" == "" ]]; then
  OLDTGS=8
fi
TGS=$(gum input --value "${OLDTGS}")
gum style --foreground 212 "${TGS}"

gum style --foreground "#04B575" "Enter QSY timeout [10-15] (-1 to disable):"
QSYTIMEOUT=$(gum input --value="${QSYTIMEOUT}")
if [[ "${QSYTIMEOUT}" == "" ]]; then
  QSYTIMEOUT=15
fi
gum style --foreground 212 -- "${QSYTIMEOUT}"

gum style --foreground "#04B575" "Enter AF output volume [50-80] (default 80):"
AFVOL=$(gum input --value "${OLDAFVOL}")
if [[ "${AFVOL}" == "" ]]; then
  RFVOL=80
fi
gum style --foreground 212 "${AFVOL}"

gum style --foreground "#04B575" "Enter RF input volume [17-23] (default 19):"
RFVOL=$(gum input --value "${OLDRFVOL}")
if [[ "${RFVOL}" == "" ]]; then
  RFVOL=19
fi
gum style --foreground 212 "${RFVOL}"

gum style --foreground "#04B575" "Enter RF compression [1-8] (default 2):"
CPVOL=$(gum input --value "${OLDCPVOL}")
if [[ "${CPVOL}" == "" ]]; then
  RFVOL=2
fi
gum style --foreground 212 "${CPVOL}"

EPOCH=$(date +%s)

gum confirm "Commit changes?"

RESULT=$?
if [ $RESULT -eq 0 ]; then
  say "Backup old config"
  run "cp /etc/svxlink/svxlink.conf /tmp/svxlink.conf.${EPOCH}"
  run "cp /etc/svxlink/node_info.json /tmp/node_info.json.${EPOCH}"
  run "rm -f /tmp/svxlink.conf"
  say "Downloading latest sa818 firmware module"
  run "wget -O /usr/local/bin/sa818 https://raw.githubusercontent.com/Guru-RF/SA818/main/sa818.py > /dev/null 2>&1"
  say "Downloading latest config template"
  run "wget -O /tmp/svxlink.conf https://raw.githubusercontent.com/Guru-RF/SVXSpot/master/svxlink-6.6.conf > /dev/null 2>&1"
  run "wget -O /tmp/node_info.json https://raw.githubusercontent.com/Guru-RF/SVXSpot/master/node_info.json > /dev/null 2>&1"
  say "Applying configuration"
  cp /tmp/svxlink.conf /etc/svxlink/svxlink.conf
  cp /tmp/node_info.json /etc/svxlink/node_info.json
	perl -i -pe "s/--HOST--/${REFLECTOR}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--CALL--/${CALL}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--TG--/${TG}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--TGS--/${TGS}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--CALL--/${CALL}/g" /etc/svxlink/node_info.json
	perl -i -pe "s/--SVXCALL--/${SVXCALL}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--SVXPWD--/${SVXPWD}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--QSYTIMEOUT--/${QSYTIMEOUT}/g" /etc/svxlink/svxlink.conf
	perl -i -pe "s/--LOCATION--/${LOCATION}/g" /etc/svxlink/node_info.json
	perl -i -pe "s/--LAT--/${LAT}/g" /etc/svxlink/node_info.json
	perl -i -pe "s/--LON--/${LON}/g" /etc/svxlink/node_info.json
	perl -i -pe "s/--LOC--/${LOC}/g" /etc/svxlink/node_info.json
	perl -i -pe "s/--HIDDEN--/${HIDDEN,,}/g" /etc/svxlink/node_info.json
	rm /usr/sbin/hotspot
  say "Configuring hotspot"
  echo "#!/bin/bash" > /usr/sbin/hotspot
  echo "" >> /usr/sbin/hotspot
  echo "sa818 --port /dev/ttyAMA0 volume --level ${CPVOL}" >> /usr/sbin/hotspot
  if [[ "${CTCSSTX}" == "Yes" ]]; then
    echo "sa818 --port /dev/ttyAMA0 radio --frequency ${FREQ} --ctcss ${TONE},${TONE} --close-tail yes" >> /usr/sbin/hotspot
  else
    echo "sa818 --port /dev/ttyAMA0 radio --frequency ${FREQ} --ctcss 0,${TONE} --close-tail yes" >> /usr/sbin/hotspot
  fi
  echo "sa818 --port /dev/ttyAMA0 filters --emphasis yes --highpass no --lowpass no" >> /usr/sbin/hotspot
	chmod +x /usr/sbin/hotspot
  /usr/sbin/hotspot
  say "Configuring hotspot volume"
  echo "#!/bin/bash" > /usr/sbin/hotspot_volume
  echo "" >> /usr/sbin/hotspot_volume
  echo "# audio to radio Module" >> /usr/sbin/hotspot_volume
  echo "amixer set 'Headphone' ${AFVOL}%" >> /usr/sbin/hotspot_volume
  echo "# audio from radio Module" >> /usr/sbin/hotspot_volume
  echo "amixer set 'Capture' ${RFVOL}%" >> /usr/sbin/hotspot_volume
  echo "" >> /usr/sbin/hotspot_volume
  echo "
# Disable ALC en Deemphasis
amixer cset iface=MIXER,name='DAC Deemphasis Switch' 0
amixer cset iface=MIXER,name='ALC Function' 0
amixer cset iface=MIXER,name='ALC Target' 0
amixer cset iface=MIXER,name='ALC Mode' 1
amixer cset iface=MIXER,name='ALC Attack' 0
amixer cset iface=MIXER,name='ALC Decay' 0
amixer cset iface=MIXER,name='ALC Hold Time' 0
amixer cset iface=MIXER,name='ALC Max Gain' 0
amixer cset iface=MIXER,name='ALC Min Gain' 0
amixer cset iface=MIXER,name='ADC High Pass Filter Switch' 0" >> /usr/sbin/hotspot_volume
  /usr/sbin/hotspot_volume > /dev/null 2>&1
	systemctl restart svxlink
  say "Send CTCSS ${TONE} to ${FREQ} with D1# to activate the parrot (to test audio levels)"
  say "Send CTCSS ${TONE} to ${FREQ} once activate the repeater talkgroup TG8, next PTT you are life on the repeater network !"
  say "You here a small two-tone when we are back in listening mode on TG0, when there is traffic on TG8 it will be automaticaly activated !"
else
gum style --foreground "#04B575" "Abort!"
fi
