#!/bin/bash

VAL=1

/usr/bin/wm8960-soundcard

while [[ "${VAL}" != "0" ]]
do
        echo "Waiting for sound driver"
        aplay -l | grep wm8960soundcard
        VAL=$?
        sleep 1
done

/usr/sbin/hotspot_volume
