#!/bin/bash

FILE=/tmp/state
SVXMSG=/tmp/svxlink-message

if test -f "${FILE}"; then
	STATE=$(cat ${FILE})
else
	echo offline > ${FILE}
	STATE=$(cat ${FILE})
fi

if : >/dev/tcp/35.189.215.208/443; then
	if [ "${STATE}" == "online" ]; then
		echo "still online"
	else
		rm -f ${FILE}
		echo "online" > ${FILE}
		echo "online" > ${SVXMSG}
		chown svxlink ${FILE}
                chown svxlink ${SVXMSG}
	fi
else
	if [ "${STATE}" == "offline" ]; then
		echo "still offline"
	else	
		rm -f ${FILE}
		echo "offline" > ${FILE}
		echo "offline" > ${SVXMSG}
		chown svxlink ${FILE}
                chown svxlink ${SVXMSG}
	fi
fi
